### ISSUE TITLE
Is typings solid?

### ISSUE THREAD

**Issue by oivvio** [typings/api#53]
Today I started a new TypeScript project and tsd told me it was deprecated I should go try typings. So here I am.

8 hours ago this search `typings search electron --limit 200 --source dt` generated 32 hits right now it generating 6 hits.

Is that a result of something changing upstream? Could it be something I'm doing.

**Comment by blakeembrey** [comment]
Old entries are being marked as deprecated and not showing up in search results anymore. If you look, this commit: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/984183292fa6381742ac1676742fd8e220d92b82 was just merged recently which merged the type definitions back into a single file instead of 25 separate ones.

**Comment by blakeembrey** [comment]
Relevant PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8732#issuecomment-206313228. Merged 7 hours ago. Typings is completely up to date there, so I don't see the issue?

**Comment by oivvio** [comment]
My bad.

**Comment by blakeembrey** [comment]
All good, it's a new behavior to hide/deprecate old versions like that. Can't tell if it's the best decision long term yet.
